# Generated by Django 3.0.5 on 2020-04-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
