# Generated by Django 3.0.5 on 2020-04-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0004_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='phone',
        ),
    ]
