# Generated by Django 3.0.5 on 2020-04-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0005_auto_20200423_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='text',
            new_name='message',
        ),
    ]
