# Generated by Django 3.0.5 on 2020-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0013_auto_20200425_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='read/img/df.jpeg', upload_to='read/img'),
        ),
    ]
