# Generated by Django 3.0.5 on 2020-04-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0014_auto_20200425_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='read/img/IMG_20150810_183603.jpg', upload_to='read/img'),
        ),
    ]
