# Generated by Django 3.0.5 on 2020-05-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0021_following_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='following',
        ),
    ]
