# Generated by Django 3.0.5 on 2020-05-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0022_remove_following_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
