# Generated by Django 3.0.5 on 2020-05-04 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('read', '0028_mysave_save'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Save',
            new_name='SavePost',
        ),
    ]
