# Generated by Django 3.0.5 on 2020-05-06 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('read', '0030_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='following_tag',
            field=models.ManyToManyField(blank=True, related_name='Hash_name', to='read.HashTag'),
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
