# Generated by Django 3.0.5 on 2020-05-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0035_mynotifacions_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
