# Generated by Django 3.0.5 on 2020-05-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0037_notifications_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mynotifacions',
            old_name='notifcations',
            new_name='notifications',
        ),
    ]
