# Generated by Django 3.0.5 on 2020-05-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0038_auto_20200519_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='read.Post'),
        ),
    ]
