# Generated by Django 3.0.5 on 2020-05-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0043_auto_20200519_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
