# Generated by Django 3.0.5 on 2020-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0044_remove_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTP', models.CharField(default=0, max_length=4)),
                ('Email', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
