# Generated by Django 3.0.5 on 2020-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0045_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pass',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(default=' ', max_length=10000),
        ),
    ]
